//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourcesLibrary {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResourcesLibrary.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AND.
        /// </summary>
        public static string AND {
            get {
                return ResourceManager.GetString("AND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BILLION.
        /// </summary>
        public static string BILLION {
            get {
                return ResourceManager.GetString("BILLION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EIGHT.
        /// </summary>
        public static string EIGHT {
            get {
                return ResourceManager.GetString("EIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EIGHTEEN.
        /// </summary>
        public static string EIGHTEEN {
            get {
                return ResourceManager.GetString("EIGHTEEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EIGHTY.
        /// </summary>
        public static string EIGHTY {
            get {
                return ResourceManager.GetString("EIGHTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ELEVEN.
        /// </summary>
        public static string ELEVEN {
            get {
                return ResourceManager.GetString("ELEVEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIFTEEN.
        /// </summary>
        public static string FIFTEEN {
            get {
                return ResourceManager.GetString("FIFTEEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIFTY.
        /// </summary>
        public static string FIFTY {
            get {
                return ResourceManager.GetString("FIFTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIVE.
        /// </summary>
        public static string FIVE {
            get {
                return ResourceManager.GetString("FIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FORTY.
        /// </summary>
        public static string FORTY {
            get {
                return ResourceManager.GetString("FORTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOUR.
        /// </summary>
        public static string FOUR {
            get {
                return ResourceManager.GetString("FOUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOURTEEN.
        /// </summary>
        public static string FOURTEEN {
            get {
                return ResourceManager.GetString("FOURTEEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HUNDRED.
        /// </summary>
        public static string HUNDRED {
            get {
                return ResourceManager.GetString("HUNDRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MILLION.
        /// </summary>
        public static string MILLION {
            get {
                return ResourceManager.GetString("MILLION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MINUS.
        /// </summary>
        public static string MINUS {
            get {
                return ResourceManager.GetString("MINUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NINE.
        /// </summary>
        public static string NINE {
            get {
                return ResourceManager.GetString("NINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NINETEEN.
        /// </summary>
        public static string NINETEEN {
            get {
                return ResourceManager.GetString("NINETEEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NINETY.
        /// </summary>
        public static string NINETY {
            get {
                return ResourceManager.GetString("NINETY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ONE.
        /// </summary>
        public static string ONE {
            get {
                return ResourceManager.GetString("ONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUADRILLION.
        /// </summary>
        public static string QUADRILLION {
            get {
                return ResourceManager.GetString("QUADRILLION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEVEN.
        /// </summary>
        public static string SEVEN {
            get {
                return ResourceManager.GetString("SEVEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEVENTEEN.
        /// </summary>
        public static string SEVENTEEN {
            get {
                return ResourceManager.GetString("SEVENTEEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEVENTY.
        /// </summary>
        public static string SEVENTY {
            get {
                return ResourceManager.GetString("SEVENTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIX.
        /// </summary>
        public static string SIX {
            get {
                return ResourceManager.GetString("SIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIXTEEN.
        /// </summary>
        public static string SIXTEEN {
            get {
                return ResourceManager.GetString("SIXTEEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIXTY.
        /// </summary>
        public static string SIXTY {
            get {
                return ResourceManager.GetString("SIXTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEN.
        /// </summary>
        public static string TEN {
            get {
                return ResourceManager.GetString("TEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THIRTEEN.
        /// </summary>
        public static string THIRTEEN {
            get {
                return ResourceManager.GetString("THIRTEEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THIRTY.
        /// </summary>
        public static string THIRTY {
            get {
                return ResourceManager.GetString("THIRTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THOUSAND.
        /// </summary>
        public static string THOUSAND {
            get {
                return ResourceManager.GetString("THOUSAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THREE.
        /// </summary>
        public static string THREE {
            get {
                return ResourceManager.GetString("THREE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRILLION.
        /// </summary>
        public static string TRILLION {
            get {
                return ResourceManager.GetString("TRILLION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TWELVE.
        /// </summary>
        public static string TWELVE {
            get {
                return ResourceManager.GetString("TWELVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TWENTY.
        /// </summary>
        public static string TWENTY {
            get {
                return ResourceManager.GetString("TWENTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TWO.
        /// </summary>
        public static string TWO {
            get {
                return ResourceManager.GetString("TWO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZERO.
        /// </summary>
        public static string ZERO {
            get {
                return ResourceManager.GetString("ZERO", resourceCulture);
            }
        }
    }
}
